<?php

namespace AppBundle\Repository;

/**
 * ContactListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactListRepository extends \Doctrine\ORM\EntityRepository
{
}
